# Generated by Django 3.2 on 2021-04-08 08:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0001_initial'),
        ]

    operations = [
        migrations.AlterField(
                model_name='customuser',
                name='id',
                field=models.AutoField(primary_key=True, serialize=False),
                ),
        ]
