# Generated by Django 3.2 on 2021-04-08 08:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ]

    operations = [
        migrations.CreateModel(
                name='Project',
                fields=[
                    ('id',
                     models.AutoField(auto_created=True, primary_key=True,
                                      serialize=False, verbose_name='ID')),
                    ('name', models.CharField(max_length=255)),
                    ],
                ),
        migrations.CreateModel(
                name='TypeOfWork',
                fields=[
                    ('id',
                     models.AutoField(auto_created=True, primary_key=True,
                                      serialize=False, verbose_name='ID')),
                    ('label', models.CharField(max_length=255)),
                    ],
                ),
        migrations.CreateModel(
                name='WorkReport',
                fields=[
                    ('id',
                     models.AutoField(auto_created=True, primary_key=True,
                                      serialize=False, verbose_name='ID')),
                    ('description', models.TextField(null=True)),
                    ('arrival', models.TextField(null=True)),
                    ('departure', models.TextField(null=True)),
                    ('productive_time',
                     models.DurationField(default=datetime.timedelta(0))),
                    ('creat_time',
                     models.DateTimeField(auto_now_add=True, null=True)),
                    ('edit_time', models.DateTimeField(auto_now=True)),
                    ('project', models.ForeignKey(null=True,
                                                  on_delete=django.db.models.deletion.SET_NULL,
                                                  to='work_report.project')),
                    ('type_of_work', models.ForeignKey(null=True,
                                                       on_delete=django.db.models.deletion.SET_NULL,
                                                       to='work_report.typeofwork')),
                    ('worker', models.ForeignKey(null=True,
                                                 on_delete=django.db.models.deletion.SET_NULL,
                                                 to=settings.AUTH_USER_MODEL)),
                    ],
                ),
        ]
