# Generated by Django 3.2 on 2021-04-08 08:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('work_report', '0001_initial'),
        ]

    operations = [
        migrations.AlterField(
                model_name='project',
                name='id',
                field=models.AutoField(primary_key=True, serialize=False),
                ),
        migrations.AlterField(
                model_name='typeofwork',
                name='id',
                field=models.AutoField(primary_key=True, serialize=False),
                ),
        migrations.AlterField(
                model_name='workreport',
                name='id',
                field=models.AutoField(primary_key=True, serialize=False),
                ),
        ]
