# Generated by Django 3.2 on 2021-04-14 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_report', '0004_auto_20210414_0847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='typeofwork',
            name='label',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
