# Generated by Django 3.2 on 2021-04-14 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_report', '0005_auto_20210414_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='typeofwork',
            name='label',
            field=models.CharField(max_length=255),
        ),
    ]
